package laboratorio.http.routes;


public enum Uri {  
    ROOT,
    LOGIN, 
    REGISTER, 
    ORIGENES_SIMPLIFICADOS,
    ORIGEN,
    MYORIGEN, 
    UPDATE,
    UPDATEMY,
    CHANGE_STATE,
    ORDEN_INDIVIDUAL,
    ORDENES_EXCEL,
    DERIVACIONES,
    ORDEN_DERIVACION,
    RESULTADO,
    PDF_TEMPLATE_INSTRUCTIVO_LOAD,
    EXCEL_TEMPLATE_DERIVACION_LOTE_LOAD,
    PDF_TEMPLATE_INSTRUCTIVO_GET,
    EXCEL_TEMPLATE_DERIVACION_LOTE_GET,
    ACTUALIZACION_FLAG_DECARGA_ORDEN
}